runtime: go111

handlers:
# Configure App Engine to serve any static assets.
- url: /static 
  static_dir: static

# Use HTTPS for all requests.
- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto